name: WizardAcademy
version: ${project.version}
main: net.craftions.wizardacademy.WizardAcademy
api-version: 1.16
authors:
  - MCTzOCK
  - Sausefix
commands:
  npc:
    permission: system.command.npc
  rundtour:
    usage: /rundtour ...
load: POSTWORLD